### PR TITLE
Feature

### PR DESCRIPTION
**Pull request by Ivankivu**
## What this PR does:

* #### Add UI files to Branch develop
  * Here, A user  signup page, login page
  * A user dashboard, Food menus
  * A user orders food type and checkout
  * A user views order history
  * An admin login, dashboard
  * An admin views orderlist, accepts, rejects and completes orders
  * An admin view food list, adds, edits, and deletes items.

## User Interface [Demo here](https://ivankivu.github.io/Fast-Food-Fast/UI)

### CODE REVIEW

**Comment by Phionamary** [comment]
@Ivankivu 
From your commit messages,  I can see that your pivotal tracker and git are not yet integrated.  One of the requirements for challenge 1 was to have pivotal tracker integrated into Git.  Please work on that. 

Otherwise,  great work on the UI

**Comment by Ivankivu** [comment]
@Phionamary  Yes it is integrated. if you notice the small three dot `...` expand to reveal the story ID for each commit

**Comment by Luleherll** [comment]
good work

**Comment by Kasulejoseph** [comment]
great UI everything is just fine

**Comment by KicaRonaldOkello** [comment]
Good work. I think it's ready for merging

**Pull request merged**
